# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tU0kMzt7GYWgIHa7eQk6TSUordcM4XmC
"""

# ZJZ twitter sentiment analysis

# import
import tweepy
from textblob import TextBlob
from wordcloud import WordCloud
import pandas as pd
import numpy as np
import re
import matplotlib.pyplot as plt
plt.style.use('fivethirtyeight')

accessToken='XXXX'
accessTokenSecret='XXXX'
consumerKey='XXXX'
consumerSecret='XXXX'
auth = tweepy.OAuthHandler(consumerKey,consumerSecret)
auth.set_access_token(accessToken,accessTokenSecret)
api=tweepy.API(auth,wait_on_rate_limit=True)

# get 100 tweets 
posts = api.user_timeline(screen_name="BillGates ",count=100,lang="en",tweet_mode="extended")

def cleanTxt(text):
  text = re.sub(r'@[A-Za-z0-9]+','',text)
  text = re.sub(r'#','',text)
  text = re.sub(r'RT[\s]+','',text)
  text = re.sub(r'https:\/\/S+','',text)
  return(text)

def getSubjectivity(text):
  return TextBlob(text).sentiment.subjectivity
def getPolarity(text):
  return TextBlob(text).sentiment.polarity

# word cloud
allWords = ' '.join([twts for twts in df['Tweets']])
wordCloud = WordCloud(width = 500,height = 300, random_state=80, max_font_size=100).generate(allWords)
plt.imshow(wordCloud,interpolation='bilinear')
plt.axis('on')
plt.show()

#NLP part
def getAnalysis(score):
  if score < 0:
    return 'Negative'
  elif score==0:
    return 'Middle'
  else:
    return 'Positive'
df['Analysis']=df['Polarity'].apply(getAnalysis)
df

plt.figure(figsize=(8,6))
for i in range(0,df.shape[0]):
  plt.scatter(df['Polarity'][i],df['Subjectivity'][i],color='Blue')
plt.xlabel('Polarity')
plt.ylabel('Subjectivity')
plt.show
